### ISSUE TITLE
15C

### ISSUE THREAD

**Issue by Sloshmold** [jonnyrider/eufy_vacuum_g10#1]
Hi,

Used your code for the 15C and got it all working except the status which shows error. for instance it should show idle, docked etc. 

did you have this issue changing the code to suit the G10?

Thanks

**Comment by jonnyrider** [comment]
I've created a separate repository for the 15C, let me know if this works:

https://github.com/jonnyrider/eufy_vacuum_15c

**Comment by Sloshmold** [comment]
Great thanks! I’ll try it tomorrow.
________________________________
